#include "mazes.h"

//types: B: bluestone, C: colorstone, E: eagle, G: greystone, M: mossy, P: purplestone, R: redbrick, W: wood

maze_t mazes[3] = {
	{ 12, 12, 144, "CESPR",
		{
			W,W,W,W,W,B,W,W,W,P,W,W,
			W,O,O,O,O,O,O,O,O,O,O,W,
			W,O,O,O,O,O,O,O,O,O,O,W,
			W,O,O,O,O,O,O,O,W,O,O,W,
			W,O,O,W,O,W,O,O,W,O,O,W,
			W,O,O,W,O,W,W,O,W,O,O,W,
			W,O,O,W,O,O,W,O,W,O,O,W,
			W,O,O,O,W,O,W,O,W,W,W,W,
			W,O,O,O,W,O,W,O,O,O,O,W,
			W,O,O,O,W,W,W,W,W,O,O,W,
			W,O,O,O,O,O,O,O,O,O,O,E,
			W,W,W,W,W,W,W,W,W,W,W,W
		}
	},
	{ 24, 24, 576, "MUDD",
		{
			W,W,W,W,W,B,W,W,W,P,W,W,W,W,W,W,W,W,W,W,W,W,W,W,
			W,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,W,
			W,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,W,
			W,O,O,O,O,O,O,O,O,O,O,O,W,O,W,W,W,W,W,W,O,O,O,C,
			W,O,O,O,O,W,O,O,O,O,W,O,W,O,O,O,O,O,O,W,O,O,O,W,
			W,O,O,W,O,W,W,O,W,O,W,O,W,O,O,O,O,O,O,W,O,O,O,W,
			W,O,O,W,O,O,W,O,W,O,W,O,W,O,W,W,W,W,W,W,O,O,O,W,
			W,O,O,O,W,O,W,O,W,O,W,O,W,O,W,O,O,O,O,O,O,O,O,W,
			W,O,O,O,W,O,W,O,W,O,W,O,W,O,W,O,W,W,W,W,W,W,W,W,
			W,O,O,O,W,O,W,O,W,O,W,O,W,O,W,O,O,O,O,O,O,O,O,W,
			W,O,O,O,W,O,W,O,W,O,W,O,W,O,O,O,O,O,O,O,O,O,O,W,
			W,O,O,O,W,O,W,O,W,O,W,O,W,O,W,W,W,W,W,W,O,W,W,W,
			W,O,W,O,W,O,W,O,W,O,O,O,W,O,O,O,O,O,W,O,O,O,O,B,
			W,O,W,O,W,O,W,O,W,W,W,W,W,W,W,W,O,O,W,O,O,O,O,W,
			W,O,W,O,W,O,W,O,O,O,O,O,O,G,O,W,O,O,W,O,O,O,O,W,
			W,O,W,O,W,O,O,W,W,W,W,W,W,W,O,W,O,O,W,O,O,O,O,W,
			W,O,W,O,W,O,O,W,O,O,O,O,O,O,O,W,O,O,W,W,W,W,W,W,
			W,O,O,O,W,O,O,W,O,O,O,O,O,O,O,W,W,O,O,O,O,O,O,W,
			W,O,O,O,W,W,W,W,O,O,O,W,O,O,O,O,O,R,O,O,O,O,O,W,
			W,O,W,O,O,O,O,O,O,O,O,W,O,O,O,W,O,W,O,O,O,O,O,E,
			W,O,W,O,O,O,O,O,O,O,O,W,O,O,O,W,O,W,O,O,O,O,O,W,
			W,W,W,W,M,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W
		}
	},
	{ 36, 36, 1296, "PUPIN",
		{
			W,W,W,W,W,B,W,W,W,P,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,
			W,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,W,
			W,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,W,
			W,O,O,O,O,O,O,O,O,O,O,O,P,O,W,W,W,W,W,W,O,O,O,O,O,O,W,W,W,W,W,W,W,W,O,W,
			W,O,O,O,O,W,O,O,O,O,W,O,W,O,O,O,O,O,O,W,O,O,O,O,O,O,W,O,O,O,O,O,O,O,O,W,
			W,O,O,W,O,W,W,O,W,O,W,O,W,O,O,O,O,O,O,W,O,O,O,O,O,O,W,O,W,W,W,W,W,W,W,W,
			W,O,O,W,O,O,W,O,W,O,W,O,W,O,W,W,W,W,W,W,O,O,O,O,O,O,W,O,O,O,O,O,O,O,O,W,
			W,O,O,O,W,O,W,O,W,O,W,O,W,O,W,O,O,O,O,O,O,O,O,O,O,O,W,O,O,O,O,O,O,O,O,W,
			W,O,O,O,W,O,W,O,W,O,W,O,W,O,W,O,W,W,W,W,W,W,W,O,O,O,W,O,O,W,O,W,W,O,O,W,
			R,O,O,O,W,O,W,O,W,O,W,O,W,O,W,O,O,O,O,O,O,O,O,O,O,O,W,O,O,W,O,O,W,O,O,W,
			W,O,O,O,W,O,W,O,W,O,W,O,W,O,O,O,O,O,O,O,O,O,O,O,O,O,W,O,O,W,O,O,W,O,O,W,
			W,O,O,O,W,O,W,O,W,O,W,O,W,O,W,W,W,W,W,W,O,W,W,W,W,W,W,O,O,W,O,O,W,O,O,W,
			W,O,W,O,W,O,W,O,W,O,O,O,W,O,O,O,O,O,W,O,O,O,O,O,O,O,W,O,O,W,O,O,W,O,O,W,
			W,O,W,O,W,O,W,O,W,W,W,W,W,W,W,W,O,O,W,O,O,O,O,O,O,O,W,O,O,W,O,O,W,O,O,W,
			W,O,W,O,W,O,W,O,O,O,O,O,O,W,O,W,O,O,W,O,O,O,O,O,O,O,W,O,O,W,O,O,W,O,O,W,
			W,O,W,O,W,O,O,W,W,W,W,W,W,W,O,W,O,O,W,O,O,O,O,O,O,O,W,O,O,W,O,O,W,O,O,C,
			W,O,W,O,W,O,O,W,O,O,O,O,O,O,O,W,O,O,W,W,W,W,W,O,O,O,W,O,O,W,O,O,W,O,O,W,
			W,O,O,O,W,O,O,W,O,O,O,O,O,O,O,W,W,O,O,O,O,O,O,O,O,O,W,O,O,O,W,O,W,O,O,W,
			W,O,O,O,W,W,W,W,O,O,O,C,O,O,O,O,O,W,O,O,O,O,O,O,O,O,W,O,O,O,W,O,W,O,O,W,
			W,O,W,O,O,O,O,O,O,O,O,M,O,O,O,W,O,W,O,O,O,O,O,O,O,O,W,O,O,O,W,O,W,R,W,W,
			W,O,W,O,O,O,O,O,O,O,O,W,O,O,O,W,O,W,O,O,O,O,W,W,W,W,W,O,O,W,O,O,O,O,O,W,
			W,W,W,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,W,O,O,O,O,O,O,W,O,O,O,O,O,W,
			W,O,O,O,W,O,W,O,W,O,W,O,W,O,O,O,O,O,O,O,O,O,O,O,O,W,W,W,W,W,O,O,W,O,O,W,
			W,O,O,O,W,O,W,O,W,O,W,O,W,O,W,W,W,W,W,W,O,W,W,O,O,W,O,O,O,O,O,O,W,O,O,W,
			W,O,W,O,W,O,W,O,W,O,O,O,W,O,O,O,O,O,W,O,O,O,O,O,O,O,O,O,O,O,O,O,W,O,O,W,
			W,O,W,O,W,O,W,O,W,W,W,W,W,W,W,W,O,O,W,O,O,O,O,O,O,O,O,O,O,O,O,O,W,O,O,W,
			W,O,W,O,W,O,W,O,O,O,O,O,O,W,O,W,O,O,W,O,O,O,O,O,O,W,W,W,W,W,W,W,W,W,W,W,
			W,O,W,O,W,O,O,W,W,W,W,W,W,W,O,W,O,O,W,O,O,O,O,O,O,W,O,O,O,O,O,O,O,O,O,W,
			W,O,W,O,W,O,O,W,O,O,O,O,O,O,O,W,O,O,O,W,B,W,W,W,W,W,O,O,O,O,O,O,O,O,O,W,
			W,O,O,O,W,O,O,W,O,O,O,O,O,O,O,W,W,O,O,O,O,O,O,O,O,O,W,O,O,O,O,O,O,O,O,W,
			W,O,O,O,W,B,W,W,O,O,O,W,O,O,O,O,O,W,O,O,O,O,O,O,O,O,O,O,W,W,W,O,O,O,O,W,
			W,O,W,O,O,O,O,O,O,O,O,W,O,O,O,W,O,W,O,O,O,O,O,O,W,O,O,O,O,O,W,O,O,O,O,W,
			W,O,W,O,O,O,O,O,O,O,O,W,O,O,O,W,O,W,O,O,O,O,O,O,W,O,O,O,O,O,W,O,O,O,O,E,
			W,W,W,W,W,W,W,W,W,W,M,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W
		}
	}
};
